quarkus:
  http:
    host: 0.0.0.0
    port: 8000
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:./output/db;create=true
  hibernate-orm:
    log:
      sql: true
    database:
      generation: drop-and-create
